In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import missingno as msno
import matplotlib.pyplot as plt
import time

In [3]:
df = pd.read_csv("..\\data\\Ciudades\\Cities.csv", index_col="id")
df.reset_index(drop=True, inplace=True)
df

,name,coords,start_year,url_name,country,country_state
0,Aberdeen,POINT(-2.15 57.15),2017,aberdeen,Scotland,NaN
1,Adelaide,POINT(138.6 -34.91666667),2017,adelaide,Australia,NaN
2,Algiers,POINT(3 36.83333333),2017,algiers,Algeria,NaN
3,Amsterdam,POINT(4.883333333 52.36666667),2017,amsterdam,Netherlands,NaN
4,Ankara,POINT(32.91666667 39.91666667),2017,ankara,Turkey,NaN
...,...,...,...,...,...,...
261,Nantes,POINT(-1.553889 47.217222),1877,nantes,France,NaN
262,Stockholm,POINT(18.05 59.28333333),1919,stockholm,Sweden,NaN
263,Rennes,POINT(-1.680833 48.114167),1897,rennes,France,NaN
264,Beijing,POINT(116.4166667 39.91666667),1965,beijing,China,NaN
265,London,POINT(-0.08333333333 51.53333333),1833,london,England,NaN

In [4]:
df.shape

(266, 6)

## Capa batch - Datos históricos, estadísticos descriptivos

In [5]:
## Países con más ciudades registradas
df["country"].value_counts()

country
United States    115
Canada            14
England            8
Spain              7
Australia          6
                ...
Switzerland        1
Venezuela          1
México             1
Peru               1
Sweden             1
Name: count, Length: 73, dtype: int64

In [6]:
## métricas descriptivas en año de inicio

df["start_year"].describe()

count     266.000000
mean     2002.360902
std        41.998713
min      1833.000000
25%      2017.000000
50%      2017.000000
75%      2017.000000
max      2017.000000
Name: start_year, dtype: float64

In [7]:
## Ciudades más antiguas
df.sort_values("start_year").head(10)

,name,coords,start_year,url_name,country,country_state
265,London,POINT(-0.08333333333 51.53333333),1833,london,England,NaN
86,Newcastle-on-Tyne,POINT(-1.616666667 54.96666667),1835,newcastle-on-tyne,England,NaN
70,Milan,POINT(9.166666667 45.45),1840,milan,Italy,NaN
112,Venice,POINT(12.33333333 45.43333333),1842,venice,Italy,NaN
42,Edinburgh,POINT(-3.166666667 55.91666667),1846,edinburgh,Scotland,NaN
245,Barcelona,POINT(2.15 41.38333333),1848,barcelona,Spain,NaN
254,Santiago,POINT(-70.6544495 -33.453214),1850,santiago-de-chile,Chile,NaN
60,Lisbon,POINT(-9.15 38.73333333),1859,lisbon,Portugal,NaN
99,São Paulo,POINT(-46.6363621 -23.5453402),1860,sao-paulo,Brazil,NaN
71,Lyons,POINT(4.833333333 45.75),1862,lyons,France,NaN

## Capa Stream - Datos fluidos (hipotético)

In [8]:
## ciudades con baja representación:
conteo_paises = df["country"].value_counts()

try:
    
    for _, fila in df.iterrows():

        time.sleep(1)
    
        pais = fila["country"]
        ciudad = fila["name"]

        if conteo_paises[pais] < 3:

            print(
                f"""
    LOW REPRESENTATION ALERT

    City: {ciudad}
    Country: {pais}

    Only {conteo_paises[pais]} city(s) from this country
    are present in the historical dataset.
"""
        )

LOW REPRESENTATION ALERT

City: Algiers
Country: Algeria

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Amsterdam
Country: Netherlands

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Ankara
Country: Turkey

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Asunción
Country: Paraguay

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Athens
Country: Greece

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Auckland
Country: New Zealand

Only 2 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Bangkok
Country: Thailand

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Belfast
Country: Northern Ireland

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Belgrade
Country: Serbia

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Brussels
Country: Belgium

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Bucharest
Country: Romania

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Budapest
Country: Hungary

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Cairo
Country: Egypt

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Cayenne
Country: French Guiana

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Copenhagen
Country: Denmark

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Dakar
Country: Senegal

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Djibouti
Country: Djibouti

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Dublin
Country: Ireland

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Georgetown
Country: Guyana

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Guatemala City
Country: Guatemala

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Guayaquil
Country: Ecuador

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Hammerfest
Country: Norway

Only 2 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Havana
Country: Cuba

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Helsinki
Country: Finland

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Hobart
Country: Tasmania

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Jakarta
Country: Indonesia

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Kingston
Country: Jamaica

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Kinshasa
Country: Congo

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Kuala Lumpur
Country: Malaysia

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: La Paz
Country: Bolivia

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Lisbon
Country: Portugal

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Manila
Country: Philippines

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Mecca
Country: Saudi Arabia

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Montevideo
Country: Uruguay

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Nairobi
Country: Kenya

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Odessa
Country: Ukraine

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Oslo
Country: Norway

Only 2 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Panama City
Country: Panama

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Paramaribo
Country: Suriname

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Port Moresby
Country: Papua New Guinea

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Prague
Country: Czech Republic

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Rangoon
Country: Myanmar

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Reykjavík
Country: Iceland

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Singapore
Country: Singapore

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Sofia
Country: Bulgaria

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Tananarive
Country: Madagascar

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Teheran
Country: Iran

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Tripoli
Country: Libya

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Warsaw
Country: Poland

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Wellington
Country: New Zealand

Only 2 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Zürich
Country: Switzerland

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Medellín
Country: Colombia

Only 2 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Caracas
Country: Venezuela

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Guadalajara
Country: México

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Lima
Country: Peru

Only 1 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Bogotá
Country: Colombia

Only 2 city(s) from this country
are present in the historical dataset.


LOW REPRESENTATION ALERT

City: Stockholm
Country: Sweden

Only 1 city(s) from this country
are present in the historical dataset.